version: "3.9"

#image https://github.com/informix/informix-dockerhub-readme/blob/master/14.10.FC6/informix-developer-database.md

services:
  informix:
    image: "ibmcom/informix-developer-database:latest"
    ports:
      - "9088:9088"
      - "9089:9089"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    environment:
      LICENSE: "accept"
      #default user informix, passoword in4mix
    volumes:
      - "./ifx_data:/opt/ibm/data"
